# Generated by Django 4.0.5 on 2022-06-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('annual_fee', models.IntegerField(max_length=5)),
                ('foreign_fee', models.FloatField(max_length=5)),
                ('base_reward_rate', models.FloatField(max_length=5)),
                ('regular_APR', models.FloatField(max_length=5)),
                ('pro_1', models.CharField(default=None, max_length=75)),
                ('pro_2', models.CharField(default=None, max_length=75)),
                ('pro_3', models.CharField(default=None, max_length=75)),
                ('con_1', models.CharField(default=None, max_length=75)),
                ('con_2', models.CharField(default=None, max_length=75)),
                ('con_3', models.CharField(default=None, max_length=75)),
            ],
        ),
    ]
