# Generated by Django 4.0.6 on 2022-07-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
