# Generated by Django 4.0.5 on 2022-06-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='annual_fee',
        ),
    ]
