# Generated by Django 4.0.5 on 2022-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_remove_creditcard_annual_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='annual_fee',
            field=models.IntegerField(default=None),
        ),
    ]
