# Generated by Django 4.0.5 on 2022-06-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuers', '0001_initial'),
        ('credit_cards', '0002_creditcard_cash_back_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='issuer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='issuers.issuer'),
        ),
    ]
