name:
  Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Check out repo code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pipenv'

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel

    - name: Install dependencies
      run: |
        pipenv install

    - name: Connect to PostgreSQL
      run: |
        pipenv run python manage.py migrate
        pipenv run python manage.py runserver
      env: 
        HOST: localhost
        PORT: 5432
        USER: postgres
        PASSWORD: postgres
        SECRET_KEY: {{secrets.SECRET}}
        DEBUG: True

    - name: Run Tests
      run: |
        pipenv run ./manage.py test